In [13]:
import numpy as np
import pandas as pd

In [53]:
intParticle = pd.read_csv('IntParticle37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])

In [54]:
motorno = intParticle.iloc[4:5,1:2].values

In [55]:
motorNo = int( np.int_(motorno) )
motorNo

10

In [56]:
intParticle = intParticle.drop(['nan','nan2'], axis=1)

In [57]:
intParticle1 = intParticle.drop(intParticle.index[motorNo+5:intParticle.index[-1]+1])

In [58]:
intParticle2 = intParticle1.drop(intParticle1.index[0:5])

In [81]:
intParticle2 = intParticle2.values

In [82]:
intParticle2

array([['4.20193', '0.15416', '0.00000'],
       ['4.17063', '0.15453', '0.00000'],
       ['4.25012', '0.17021', '0.00000'],
       ['4.62099', '0.34917', '0.00000'],
       ['5.06098', '0.76535', '0.00000'],
       ['4.94207', '0.63751', '0.00000'],
       ['4.91644', '0.61877', '0.00000'],
       ['4.93585', '0.59477', '0.00000'],
       ['5.47755', '0.90763', '0.00000'],
       ['5.62394', '0.92335', '0.00000']], dtype=object)

In [65]:
MotorSpecie1 = pd.read_csv('MotorSpecie1_37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])

In [69]:
Sp1no = MotorSpecie1.iloc[4:5,1:2].values
Sp1No = int( np.int_(Sp1no) )
Sp1No

63039

In [75]:
MotorSpecie1_ = MotorSpecie1.drop(['nan','nan2'], axis=1)
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[Sp1No+5:MotorSpecie1_.index[-1]+1])
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[0:5])

In [79]:
MotorSpecie1_ = MotorSpecie1_.values

In [80]:
MotorSpecie1_

array([['3.25291', '-0.86166', '0.00000'],
       ['1.53932', '0.64305', '0.00000'],
       ['1.05113', '1.39817', '0.00000'],
       ...,
       ['6.47699', '2.63564', '0.00000'],
       ['6.58331', '2.15061', '0.00000'],
       ['6.77594', '1.10671', '0.00000']], dtype=object)

In [86]:
np.sum( np.all( np.equal(MotorSpecie1_,intParticle2), axis=1) )

ValueError: operands could not be broadcast together with shapes (63039,3) (10,3) 

In [87]:
sth = np.insert(intParticle2,2,np.nan, axis=0)

In [88]:
sth

array([['4.20193', '0.15416', '0.00000'],
       ['4.17063', '0.15453', '0.00000'],
       [nan, nan, nan],
       ['4.25012', '0.17021', '0.00000'],
       ['4.62099', '0.34917', '0.00000'],
       ['5.06098', '0.76535', '0.00000'],
       ['4.94207', '0.63751', '0.00000'],
       ['4.91644', '0.61877', '0.00000'],
       ['4.93585', '0.59477', '0.00000'],
       ['5.47755', '0.90763', '0.00000'],
       ['5.62394', '0.92335', '0.00000']], dtype=object)

In [90]:
emp = np.empty((3,3))

In [91]:
emp[:] = np.nan

In [92]:
emp

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [93]:
sm = np.empty((3,3))
sm

array([[6.93404565e-310, 5.30276956e+180, 1.57076922e-076],
       [4.57752921e-071, 3.86226062e-086, 3.35709102e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180]])

In [98]:
sm2 = np.append(sm,emp,axis=0)
sm2

array([[6.93404565e-310, 5.30276956e+180, 1.57076922e-076],
       [4.57752921e-071, 3.86226062e-086, 3.35709102e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan]])

In [99]:
MotorSpecie1_.shape

(63039, 3)

In [100]:
intParticle2.shape

(10, 3)

In [103]:
shp = MotorSpecie1_.shape[0] - intParticle2.shape[0]

In [104]:
nemp = np.empty((shp,3))
nemp[:] = np.nan
intParticle2_ = np.append(intParticle2,nemp,axis=0)

In [105]:
intParticle2_.shape

(63039, 3)

In [107]:
intParticle2_

array([['4.20193', '0.15416', '0.00000'],
       ['4.17063', '0.15453', '0.00000'],
       ['4.25012', '0.17021', '0.00000'],
       ...,
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]], dtype=object)

In [108]:
intParticle2

array([['4.20193', '0.15416', '0.00000'],
       ['4.17063', '0.15453', '0.00000'],
       ['4.25012', '0.17021', '0.00000'],
       ['4.62099', '0.34917', '0.00000'],
       ['5.06098', '0.76535', '0.00000'],
       ['4.94207', '0.63751', '0.00000'],
       ['4.91644', '0.61877', '0.00000'],
       ['4.93585', '0.59477', '0.00000'],
       ['5.47755', '0.90763', '0.00000'],
       ['5.62394', '0.92335', '0.00000']], dtype=object)

In [111]:
chk = 1*np.equal(MotorSpecie1_,intParticle2_)

In [112]:
chk[:,0]

array([0, 0, 0, ..., 0, 0, 0])

In [113]:
np.sum(chk[:,0])

0

In [119]:
MotorSpecie1_[187]

array(['4.20193', '0.15416', '0.00000'], dtype=object)

In [120]:
intParticle2_[0]

array(['4.20193', '0.15416', '0.00000'], dtype=object)

In [129]:
np.equal(MotorSpecie1_[187],intParticle2_[0])

array([ True,  True,  True])

In [122]:
chk[187]

array([0, 0, 0])

In [124]:
intParticle2.shape

(10, 3)

In [127]:
intParticle2[motorNo-1]

array(['5.62394', '0.92335', '0.00000'], dtype=object)

In [139]:
if (sum(1*np.equal(MotorSpecie1_[187],intParticle2_[0])) == 3):
    print('all rows equal')

all rows equal


In [141]:
smt = 0; count=0
while smt < motorNo:
    for i in range(0,MotorSpecie1_.shape[0]):
        if(np.sum(1*np.equal(MotorSpecie1_[i],intParticle2_[smt])) == 3):
            count = count+1
    smt = smt+1
count

10

In [153]:
intParticle = pd.read_csv('IntParticle37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])
motorno = intParticle.iloc[4:5,1:2].values
motorNo = int( np.int_(motorno) )

intParticle = intParticle.drop(['nan','nan2'], axis=1)
intParticl = intParticle.drop(intParticle.index[motorNo+5:intParticle.index[-1]+1])
intPartic = intParticl.drop(intParticl.index[0:5])
intPartic = intPartic.values

MotorSpecie1 = pd.read_csv('MotorSpecie1_37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])
Sp1no = MotorSpecie1.iloc[4:5,1:2].values
Sp1No = int( np.int_(Sp1no) )

MotorSpecie1_ = MotorSpecie1.drop(['nan','nan2'], axis=1)
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[Sp1No+5:MotorSpecie1_.index[-1]+1])
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[0:5])
MotorSpecie1_ = MotorSpecie1_.values

activeM=0
for k in range(0, motorNo):
    for i in range(0,MotorSpecie1_.shape[0]):
        if(np.sum(1*np.equal(MotorSpecie1_[i],intPartic[k])) == 3):
            activeM = activeM+1

print("active motors =", activeM, "zombie motors =", motorNo-activeM)

active motors = 10 zombie motors = 0


In [147]:
MotorSpecie1_.shape

(63039, 3)

In [156]:
activeATP50 = np.loadtxt('Abm_no673ATP50R0.3.csv')
activeATP50.mean()

39.34

In [157]:
activeATP50.std()

6.444563600430986

In [158]:
activeATP100 = np.loadtxt('Abm_no673ATP100R0.3.csv')
activeATP100.mean()

25.462

In [159]:
activeATP100.std()

4.931182008403259

In [160]:
activeATP200 = np.loadtxt('Abm_no673ATP200R0.3.csv')
activeATP200.mean()

16.798

In [161]:
activeATP200.std()

4.712238958287238