In [170]:
import numpy as np
import pandas as pd
import time

In [2]:
intParticle = pd.read_csv('IntParticle37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])

In [3]:
motorno = intParticle.iloc[4:5,1:2].values

In [4]:
motorNo = int( np.int_(motorno) )
motorNo

10

In [5]:
intParticle = intParticle.drop(['nan','nan2'], axis=1)

In [6]:
intParticle1 = intParticle.drop(intParticle.index[motorNo+5:intParticle.index[-1]+1])

In [7]:
intParticle2 = intParticle1.drop(intParticle1.index[0:5])

In [8]:
intParticle2 = intParticle2.values

In [9]:
intParticle2

array([['4.20193', '0.15416', '0.00000'],
       ['4.17063', '0.15453', '0.00000'],
       ['4.25012', '0.17021', '0.00000'],
       ['4.62099', '0.34917', '0.00000'],
       ['5.06098', '0.76535', '0.00000'],
       ['4.94207', '0.63751', '0.00000'],
       ['4.91644', '0.61877', '0.00000'],
       ['4.93585', '0.59477', '0.00000'],
       ['5.47755', '0.90763', '0.00000'],
       ['5.62394', '0.92335', '0.00000']], dtype=object)

In [10]:
MotorSpecie1 = pd.read_csv('MotorSpecie1_37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])

/home/nitta/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (0,1,2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [11]:
Sp1no = MotorSpecie1.iloc[4:5,1:2].values
Sp1No = int( np.int_(Sp1no) )
Sp1No

63039

In [12]:
MotorSpecie1_ = MotorSpecie1.drop(['nan','nan2'], axis=1)
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[Sp1No+5:MotorSpecie1_.index[-1]+1])
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[0:5])

In [13]:
MotorSpecie1_ = MotorSpecie1_.values

In [14]:
MotorSpecie1_

array([['3.25291', '-0.86166', '0.00000'],
       ['1.53932', '0.64305', '0.00000'],
       ['1.05113', '1.39817', '0.00000'],
       ...,
       ['6.47699', '2.63564', '0.00000'],
       ['6.58331', '2.15061', '0.00000'],
       ['6.77594', '1.10671', '0.00000']], dtype=object)

In [15]:
np.sum( np.all( np.equal(MotorSpecie1_,intParticle2), axis=1) )

ValueError: operands could not be broadcast together with shapes (63039,3) (10,3) 

In [16]:
sth = np.insert(intParticle2,2,np.nan, axis=0)

In [17]:
sth

array([['4.20193', '0.15416', '0.00000'],
       ['4.17063', '0.15453', '0.00000'],
       [nan, nan, nan],
       ['4.25012', '0.17021', '0.00000'],
       ['4.62099', '0.34917', '0.00000'],
       ['5.06098', '0.76535', '0.00000'],
       ['4.94207', '0.63751', '0.00000'],
       ['4.91644', '0.61877', '0.00000'],
       ['4.93585', '0.59477', '0.00000'],
       ['5.47755', '0.90763', '0.00000'],
       ['5.62394', '0.92335', '0.00000']], dtype=object)

In [18]:
emp = np.empty((3,3))

In [19]:
emp[:] = np.nan

In [20]:
emp

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [21]:
sm = np.empty((3,3))
sm

array([[6.91659104e-310, 6.91659104e-310, 6.91659104e-310],
       [6.91659104e-310, 6.91659104e-310, 6.91659104e-310],
       [6.91659104e-310, 6.91659104e-310, 6.91659104e-310]])

In [22]:
sm2 = np.append(sm,emp,axis=0)
sm2

array([[6.91659104e-310, 6.91659104e-310, 6.91659104e-310],
       [6.91659104e-310, 6.91659104e-310, 6.91659104e-310],
       [6.91659104e-310, 6.91659104e-310, 6.91659104e-310],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan]])

In [23]:
MotorSpecie1_.shape

(63039, 3)

In [24]:
intParticle2.shape

(10, 3)

In [25]:
shp = MotorSpecie1_.shape[0] - intParticle2.shape[0]

In [26]:
nemp = np.empty((shp,3))
nemp[:] = np.nan
intParticle2_ = np.append(intParticle2,nemp,axis=0)

In [27]:
intParticle2_.shape

(63039, 3)

In [28]:
intParticle2_

array([['4.20193', '0.15416', '0.00000'],
       ['4.17063', '0.15453', '0.00000'],
       ['4.25012', '0.17021', '0.00000'],
       ...,
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]], dtype=object)

In [29]:
intParticle2

array([['4.20193', '0.15416', '0.00000'],
       ['4.17063', '0.15453', '0.00000'],
       ['4.25012', '0.17021', '0.00000'],
       ['4.62099', '0.34917', '0.00000'],
       ['5.06098', '0.76535', '0.00000'],
       ['4.94207', '0.63751', '0.00000'],
       ['4.91644', '0.61877', '0.00000'],
       ['4.93585', '0.59477', '0.00000'],
       ['5.47755', '0.90763', '0.00000'],
       ['5.62394', '0.92335', '0.00000']], dtype=object)

In [30]:
chk = 1*np.equal(MotorSpecie1_,intParticle2_)

In [31]:
chk[:,0]

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
np.sum(chk[:,0])

0

In [33]:
MotorSpecie1_[187]

array(['4.20193', '0.15416', '0.00000'], dtype=object)

In [34]:
intParticle2_[0]

array(['4.20193', '0.15416', '0.00000'], dtype=object)

In [35]:
np.equal(MotorSpecie1_[187],intParticle2_[0])

array([ True,  True,  True])

In [36]:
chk[187]

array([0, 0, 0])

In [37]:
intParticle2.shape

(10, 3)

In [38]:
intParticle2[motorNo-1]

array(['5.62394', '0.92335', '0.00000'], dtype=object)

In [39]:
if (sum(1*np.equal(MotorSpecie1_[187],intParticle2_[0])) == 3):
    print('all rows equal')

all rows equal


In [40]:
smt = 0; count=0
while smt < motorNo:
    for i in range(0,MotorSpecie1_.shape[0]):
        if(np.sum(1*np.equal(MotorSpecie1_[i],intParticle2_[smt])) == 3):
            count = count+1
    smt = smt+1
count

10

## Method 1

In [172]:
intParticle = pd.read_csv('IntParticle37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])
motorno = intParticle.iloc[4:5,1:2].values
motorNo = int( np.int_(motorno) )

intParticle = intParticle.drop(['nan','nan2'], axis=1)
intParticl = intParticle.drop(intParticle.index[motorNo+5:intParticle.index[-1]+1])
intPartic = intParticl.drop(intParticl.index[0:5])
intPartic = intPartic.values

MotorSpecie1 = pd.read_csv('MotorSpecie1_37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])
Sp1no = MotorSpecie1.iloc[4:5,1:2].values
Sp1No = int( np.int_(Sp1no) )

MotorSpecie1_ = MotorSpecie1.drop(['nan','nan2'], axis=1)
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[Sp1No+5:MotorSpecie1_.index[-1]+1])
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[0:5])
MotorSpecie1_ = MotorSpecie1_.values

activeM=0
tic = time.time()
for k in range(0, motorNo):
    for i in range(0,MotorSpecie1_.shape[0]):
        if(np.sum(1*np.equal(MotorSpecie1_[i],intPartic[k])) == 3):
            activeM = activeM+1
toc = time.time()
print("active motors =", activeM, "zombie motors =", motorNo-activeM, "time = ", toc-tic)

active motors = 10 zombie motors = 0 time =  5.142730712890625


In [173]:
intParticle = pd.read_csv('IntParticle37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])
motorno = intParticle.iloc[4:5,1:2].values
motorNo = int( np.int_(motorno) )

intParticle = intParticle.drop(['nan','nan2'], axis=1)
intParticl = intParticle.drop(intParticle.index[motorNo+5:intParticle.index[-1]+1])
intPartic = intParticl.drop(intParticl.index[0:5])
intPartic = intPartic.values

MotorSpecie1 = pd.read_csv('MotorSpecie1_37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])
Sp1no = MotorSpecie1.iloc[4:5,1:2].values
Sp1No = int( np.int_(Sp1no) )

MotorSpecie1_ = MotorSpecie1.drop(['nan','nan2'], axis=1)
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[Sp1No+5:MotorSpecie1_.index[-1]+1])
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[0:5])
MotorSpecie1_ = MotorSpecie1_.values

activeM=0
msp1 = MotorSpecie1_.shape[0]
tic = time.time()
for k in range(0, motorNo):
    for i in range(0,msp1):
        if(np.sum(1*np.equal(MotorSpecie1_[i],intPartic[k])) == 3):
            activeM = activeM+1
toc = time.time()
print("active motors =", activeM, "zombie motors =", motorNo-activeM, "time = ", toc-tic)

active motors = 10 zombie motors = 0 time =  4.962080001831055


In [42]:
MotorSpecie1_.shape

(63039, 3)

In [43]:
activeATP50 = np.loadtxt('Abm_no673ATP50R0.3.csv')
activeATP50.mean()

39.34

In [44]:
activeATP50.std()

6.444563600430986

In [45]:
activeATP100 = np.loadtxt('Abm_no673ATP100R0.3.csv')
activeATP100.mean()

25.462

In [46]:
activeATP100.std()

4.931182008403259

In [47]:
activeATP200 = np.loadtxt('Abm_no673ATP200R0.3.csv')
activeATP200.mean()

16.798

In [48]:
activeATP200.std()

4.712238958287238

In [76]:
ary = np.where(MotorSpecie1_ == intParticle2_)
ary[0].shape[0]

10

In [80]:
MotorSpecie1_

array([['3.25291', '-0.86166', '0.00000'],
       ['1.53932', '0.64305', '0.00000'],
       ['1.05113', '1.39817', '0.00000'],
       ...,
       ['6.47699', '2.63564', '0.00000'],
       ['6.58331', '2.15061', '0.00000'],
       ['6.77594', '1.10671', '0.00000']], dtype=object)

In [81]:
intParticle2_

array([['4.20193', '0.15416', '0.00000'],
       ['4.17063', '0.15453', '0.00000'],
       ['4.25012', '0.17021', '0.00000'],
       ...,
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]], dtype=object)

In [139]:
a = np.array([[1.56,2.56],[2.42,3.42],[4,5]])
b = np.array([[2.42,3.42],[4.1,3],[7.51,1]])
np.where(a == b)

(array([], dtype=int64), array([], dtype=int64))

In [140]:
np.array([item in b for item in a])

array([False,  True, False])

In [141]:
np.in1d(a,b)

array([False, False,  True,  True, False, False])

In [133]:
a = a.flatten()
a

array([1.56, 2.56, 2.42, 3.42, 4.  , 5.  ])

In [134]:
b = b.flatten()
b

array([2.42, 3.42, 4.1 , 3.  , 7.51, 1.  ])

In [135]:
np.where(a[:] == b[:])

(array([], dtype=int64),)

In [136]:
np.in1d(a,b)

array([False, False,  True,  True, False, False])

In [88]:
activeMx = 0
for l in range(0, 1):
    for m in range(0,a.shape[0]):
        if(np.sum(1*np.equal(a[m],b[l])) == 3):
            activeMx = activeMx+1
activeMx

1

## Method 2

In [59]:
intParticle = pd.read_csv('IntParticle37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])
motorno = intParticle.iloc[4:5,1:2].values
motorNo = int( np.int_(motorno) )

intParticle = intParticle.drop(['nan','nan2'], axis=1)
intParticl = intParticle.drop(intParticle.index[motorNo+5:intParticle.index[-1]+1])
intPartic = intParticl.drop(intParticl.index[0:5])
intPartic = intPartic.values

MotorSpecie1 = pd.read_csv('MotorSpecie1_37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])
Sp1no = MotorSpecie1.iloc[4:5,1:2].values
Sp1No = int( np.int_(Sp1no) )

MotorSpecie1_ = MotorSpecie1.drop(['nan','nan2'], axis=1)
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[Sp1No+5:MotorSpecie1_.index[-1]+1])
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[0:5])
MotorSpecie1_ = MotorSpecie1_.values

shp = MotorSpecie1_.shape[0] - intParticle2.shape[0]
nemp = np.empty((shp,3))
nemp[:] = np.nan
intParticle2_ = np.append(intParticle2,nemp,axis=0)

ary = np.where(MotorSpecie1_ == intParticle2_)
activeM = ary[0].shape[0]

activeM

10

In [89]:
np.where(MotorSpecie1_ == intParticle2_)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2]))

In [157]:
np.in1d(MotorSpecie1_[...,:-1].flatten(),intParticle2_[...,:-1].flatten())

array([False, False, False, ..., False, False, False])

In [150]:
MotorSpecie1_.flatten()

array(['3.25291', '-0.86166', '0.00000', ..., '6.77594', '1.10671',
       '0.00000'], dtype=object)

In [156]:
MotorSpecie1_[...,:-1].flatten()

array(['3.25291', '-0.86166', '1.53932', ..., '2.15061', '6.77594',
       '1.10671'], dtype=object)

In [159]:
arA = np.random.rand(3,2)
arB = np.random.rand(5,2)

In [160]:
arA

array([[0.77848001, 0.86459425],
       [0.90391294, 0.55406889],
       [0.17595285, 0.6679089 ]])

In [161]:
arB

array([[0.33737657, 0.03125244],
       [0.14658922, 0.50232964],
       [0.58953867, 0.48625264],
       [0.08261968, 0.52968782],
       [0.66452622, 0.67522755]])

In [175]:
arrA = np.insert(arA,1,[1.23456789,3.12345678],axis=0)
arrA

array([[0.77848001, 0.86459425],
       [1.23456789, 3.12345678],
       [0.90391294, 0.55406889],
       [0.17595285, 0.6679089 ]])

In [176]:
arrB = np.insert(arB,3,[1.23456789,3.12345678],axis=0)
arrB

array([[0.33737657, 0.03125244],
       [0.14658922, 0.50232964],
       [0.58953867, 0.48625264],
       [1.23456789, 3.12345678],
       [0.08261968, 0.52968782],
       [0.66452622, 0.67522755]])

In [168]:
arrB.shape[0]

6

In [180]:
count = 0
Ashp = arrA.shape[0]
Bshp = arrB.shape[0]
for i in range(0, Ashp):
    for j in range(0,Bshp):
        if(np.sum(1*np.equal(arrB[j],arrA[i])) == 2):
            count = count+1
print(count)

1


In [184]:
arrB.ndim

2

In [183]:
arrA.size

8

In [195]:
compare = np.sum(1*np.isin(arrA,arrB))
if compare%2 == 0: count = compare/2
print(count)

1.0


In [186]:
tic = time.time()
eql = np.sum(1*np.isin(intParticle2_,MotorSpecie1_))
if eql%2 == 0: activeM = eql/2
toc = time.time()
print("active motors =", activeM, "zombie motors =", motorNo-activeM, "time = ", toc-tic)

active motors = 15.0 zombie motors = -5.0 time =  618.0152537822723


In [187]:
tic = time.time()
1*np.isin(intParticle2_,MotorSpecie1_)
toc = time.time()

In [188]:
toc-tic

639.586786031723

In [189]:
600/5

120.0

In [199]:
(arrA == arrB).all()

/home/nitta/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


AttributeError: 'bool' object has no attribute 'all'

In [198]:
np.array_equiv(arrA,arrB)

False

## Method 3

In [200]:
import numpy_indexed as npi

In [218]:
intParticle = pd.read_csv('IntParticle37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])
motorno = intParticle.iloc[4:5,1:2].values
motorNo = int( np.int_(motorno) )

intParticle = intParticle.drop(['z','nan','nan2'], axis=1)
intParticl = intParticle.drop(intParticle.index[motorNo+5:intParticle.index[-1]+1])
intPartic = intParticl.drop(intParticl.index[0:5])
intPartic = intPartic.values
bindingTotal = intPartic.astype(float)

MotorSpecie1 = pd.read_csv('MotorSpecie1_37R1ATP2000MD2000.vtk', delim_whitespace=True, names=['x','y','z','nan','nan2'])
Sp1no = MotorSpecie1.iloc[4:5,1:2].values
Sp1No = int( np.int_(Sp1no) )

MotorSpecie1_ = MotorSpecie1.drop(['z','nan','nan2'], axis=1)
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[Sp1No+5:MotorSpecie1_.index[-1]+1])
MotorSpecie1_ = MotorSpecie1_.drop(MotorSpecie1_.index[0:5])
MotorSpecie1_ = MotorSpecie1_.values
activeSpecie = MotorSpecie1_.astype(float)

active_M = np.sum(1*npi.contains(bindingTotal,activeSpecie))
active_M

10

In [215]:
intPartic.astype(object)

array([['4.20193', '0.15416'],
       ['4.17063', '0.15453'],
       ['4.25012', '0.17021'],
       ['4.62099', '0.34917'],
       ['5.06098', '0.76535'],
       ['4.94207', '0.63751'],
       ['4.91644', '0.61877'],
       ['4.93585', '0.59477'],
       ['5.47755', '0.90763'],
       ['5.62394', '0.92335']], dtype=object)

In [210]:
MotorSpecie1_

array([['3.25291', '-0.86166'],
       ['1.53932', '0.64305'],
       ['1.05113', '1.39817'],
       ...,
       ['6.47699', '2.63564'],
       ['6.58331', '2.15061'],
       ['6.77594', '1.10671']], dtype=object)

In [214]:
np.random.rand(3,2)

array([[0.08845483, 0.1218009 ],
       [0.97101758, 0.89123981],
       [0.88619563, 0.67123958]])

In [224]:
tym = 3; task = 1
print("File %s took %d sec."%(task, tym))

File 1 took 3 sec.


In [225]:
#Active-Inactive motor analysis continued in the previous notebook 'ATPvel'